spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true